### PR TITLE
Added man page and modify Changelog

### PR DESCRIPTION
**Pull request by Brigobet**
I have created a man page for Debian, i think i can upload it can be used outside Debian too.

### CODE REVIEW

**Comment by Brigobet** [comment]
Nice timing, this spoils my Changelog modification. Should i close this pull-request and start another one with the right Changelog modification?

**Comment by fcambus** [comment]
Sorry, I can't accept GPL licensed documentation in this project.

Also, I would prefer the manual page to be in the [mdoc](http://mdocml.bsd.lv/man/mdoc.7.html) macro language.

**Comment by Brigobet** [comment]
Can i ask why not GPL? just curious. :)

**Comment by fcambus** [comment]
Sure. I release all my software under BSD license, either 2-Clause or 3-Clause.

**Comment by Brigobet** [comment]
I know that, i eve write the Debian copyright file about it, but i can't
see why. Do you just want one license? or you don't like GPL for your
software?

That's what i am wondering :)

2015-10-31 13:22 GMT+01:00 Frederic Cambus <notifications@github.com>:

> Sure. I release all my software under BSD license, either 2-Clause or
> 3-Clause.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fcambus/ansiweather/pull/86#issuecomment-152731781>.
>



-- 
Por limitaciones presupuestarias nos hemos visto obligados a apagar la luz
al final del túnel. Disculpen las molestias.

**Comment by fcambus** [comment]
Basically both. While I do not mind using GPL licensed software or even contributing code to them, I don't find it an acceptable license for my own software.

**Pull request closed without merging**
