### PR TITLE
Use environment shell/printf

### PR DESCRIPTION
**Pull request by andreineculau**

### CODE REVIEW

**Comment by fcambus** [comment]
AnsiWeather removed the dependency on Bash in 1.03, and is now using plain sh. This is on purpose.

**Comment by andreineculau** [comment]
ok. bad move on my side to combine 2 changes into one - forget bash. Can the printf be called without `/usr/bin`? do you want a new PR? Thanks

**Comment by fcambus** [comment]
I would love to remove the hardcoded path, but just calling printf will fail on Debian because sh is in fact dash, and dash printf is broken and doesn't display unicode characters properly.

What system are you running?

**Comment by andreineculau** [comment]
Then maybe "which printf 2>/dev/null || echo printf" is the solution

On Sun, Feb 7, 2016 at 4:35 PM, Frederic Cambus <notifications@github.com>
wrote:

> I would love to remove the hardcoded path, but just calling printf will
> fail on Debian because sh is in fact dash, and dash printf is broken and
> doesn't display unicode characters properly.
>
> What system are you running?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fcambus/ansiweather/pull/88#issuecomment-181033913>.
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by fcambus** [comment]
Sounds good to me, we could have something like print_cmd=$(which printf 2>/dev/null || echo printf) as you suggested and use the $print_cmd in place /usr/bin/printf is hardcoded.

If you submit a PR I will merge this.

**Comment by andreineculau** [comment]
new patch looks ok? thanks

**Comment by fcambus** [comment]
Haven't forgotten but I don't have access to a NetBSD box for testing at the moment, I might replug one this week.

**Comment by andreineculau** [comment]
No problem, take your time. Thanks for the status update :)

On Fri, Mar 4, 2016 at 2:45 PM, Frederic Cambus <notifications@github.com>
wrote:

> Haven't forgotten but I don't have access to a NetBSD box for testing at
> the moment, I might replug one this week.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fcambus/ansiweather/pull/88#issuecomment-192290028>.
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by fcambus** [comment]
Finally opted to use `env printf`for the two printf calls which had hardcoded path, this is cleaner this way. For info, the `xargs printf` construct ensure that we are using the printf binary instead of the shell built-in, so those calls do not need any changes.

Thanks for raising the issue in the first place.

**Pull request closed without merging**
