### PR TITLE
Remove dependency on seq and allow for custom geoip server

### PR DESCRIPTION
**Pull request by qbit**

### CODE REVIEW

**Comment by fcambus** [comment]
This looks great, I will test and merge soon.

**Comment by fcambus** [comment]
I'm wondering if it wouldn't be better to use jot as a replacement for seq, in order to avoid using eval. Maybe testing if jot exists and default on using it if so, if not try seq instead. 

For info, jot is present on FreeBSD / NetBSD / OpenBSD and also on OS X.

Any thoughts on that?

**Comment by qbit** [comment]
I had thought about using jot, but eval seemed cleaner.

I wrote a quick test to see what happens if you do something like: "forcast:; ls;". I couldn't get it to spit out anything but a syntax error (because it's still evaluating the sequence "0.." and expecting a number after.).

```
#!/usr/bin/env bash

a="4"
b="9;ls "

for i in $(seq 0 $(($a-1))); do
        echo "seq:a:$i"
done

for i in $(seq 0 $(($b-1))); do
        echo "seq:b:$i"
done

for i in $(eval echo "{0..$(($a-1))}"); do
        echo "eval:a:$i"
done

for i in $(eval echo "{0..$(($b-1))}"); do
        echo "eval:b:$i"
done
```

The eval lines give an error similar to this:
    
    -bash: 9;ls -1: syntax error: invalid arithmetic operator (error token is ";ls -1")

**Comment by qbit** [comment]
Still, probably safer to use jot.

**Comment by fcambus** [comment]
I merged the commit which allow for custom geoip server. For the first one, while I agree using eval in this context is unlikely to cause issues, I'm still paranoid by nature :-) 

I've been sleeping on it and in the end, I think the best thing to do is probably to ditch seq / jot / eval altogether and use a while loop instead.

Something like `while [ $i -lt $forecast ]` would do the trick I guess, and work everywhere.
```

**Comment by fcambus** [comment]
I pushed a commit in the `noseq` branch which implement the while loop solution. Let me know if it works for you.

Does that look like an acceptable solution?

**Comment by qbit** [comment]
Looks good to me!

**Comment by fcambus** [comment]
Great! I will merge this when I come back home.

Would it make sense to attempt getting AnsiWeather in the OpenBSD ports collection? If so, I could start making tarball releases, that was the original plan anyway.

**Comment by qbit** [comment]
Sure! You wouldn't even really need to make tarballs for it. We recently added GH_* options for pulling tags / commits from github repos!

**Comment by fcambus** [comment]
Merged. Thanks for the pointer on the GH_* options, I'll have a look. OpenBSD Porter's Handbook is in my reading list, I'll get to it soon hopefully. I have a few OpenBSD machines so I'm definitely interested in porting some stuff.

Thanks for your contributions on AnsiWeather.

**Comment by qbit** [comment]
NP! Let me know if you have any questions!

**Pull request closed without merging**
